---
- name: Copy pf.conf
  template:
    src: 'pf.conf.j2'
    dest: '/etc/pf.conf'
    mode: 0644
  notify:
    - reload pf

- name: Ensure nat jails definition file exists
  command: touch /etc/pf.table.nat-jails
    creates=/etc/pf.table.nat-jails
  notify:
    - reload pf

- name: Ensure nat jail rules definition file exists
  command: touch /etc/pf.anchor.nat-jail.conf
    creates=/etc/pf.anchor.nat-jail.conf
  notify:
    - reload pf

- name: Ensure rdr jail rules definition file exists
  command: touch /etc/pf.anchor.rdr-jail.conf
    creates=/etc/pf.anchor.rdr-jail.conf
  notify:
    - reload pf

- name: Ensure rls jail rules definition file exists
  command: touch /etc/pf.anchor.rls-jail.conf
    creates=/etc/pf.anchor.rls-jail.conf
  notify:
    - reload pf

