---
- name: Install ssmtp for easy mail forwarding
  command: pkg --rootdir {{ jail_home.stdout }} install -y ssmtp
    creates={{ jail_home.stdout }}/usr/local/sbin/ssmtp
# becomes available with ansible 2.0
#  pkgng: name=ssmtp
#         state=present
#         rootdir={{ jail_home.stdout }}

- name: Copy ssmtp.conf into place
  template:
    src=ssmtp.conf.p2
    dest={{ jail_home.stdout }}/usr/local/etc/ssmtp/ssmtp.conf

- name: Copy mailer configuration into place
  copy:
    src=mailer.conf
    dest={{ jail_home.stdout }}/etc/mail/mailer.conf
